/*
 * FenetreMessages.java
 *
 * Created on 14 févr. 2013, 12:21:17
 */
package client;

import java.awt.Dimension;
import java.awt.Rectangle;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.GroupLayout;

/**
 *
 * @author dodelien
 */
public class FenetreMessages extends javax.swing.JFrame {

	private GroupLayout.Group horizontalGroup;
	private GroupLayout.SequentialGroup sequentialGroup;

	/**
	 * Creates new form FenetreMessages
	 */
	public FenetreMessages() {
		initComponents();

		javax.swing.GroupLayout messagesPanelLayout = new javax.swing.GroupLayout(messagesPanel);
		messagesPanel.setLayout(messagesPanelLayout);

		horizontalGroup = messagesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING);
		messagesPanelLayout.setHorizontalGroup(horizontalGroup);

		GroupLayout.Group verticalGroup = messagesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING);
		sequentialGroup = messagesPanelLayout.createSequentialGroup();
		verticalGroup.addGroup(sequentialGroup);
		messagesPanelLayout.setVerticalGroup(verticalGroup);
	}

	public void afficherMessage(String pseudo, String message) {
		System.out.println(pseudo + " : " + message);
		MessagePanel messagePanel = new MessagePanel();
		messagePanel.setPseudo(pseudo + " :");
		messagePanel.setMessage(message);
		horizontalGroup.addComponent(messagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE);
		sequentialGroup.addComponent(messagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        messageTextField = new javax.swing.JTextField();
        messageLabel = new javax.swing.JLabel();
        chatScrollPane = new javax.swing.JScrollPane();
        messagesPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chat IntBD");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        messageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageTextFieldActionPerformed(evt);
            }
        });

        messageLabel.setText("Message :");

        messagesPanel.setPreferredSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout messagesPanelLayout = new javax.swing.GroupLayout(messagesPanel);
        messagesPanel.setLayout(messagesPanelLayout);
        messagesPanelLayout.setHorizontalGroup(
            messagesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );
        messagesPanelLayout.setVerticalGroup(
            messagesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 391, Short.MAX_VALUE)
        );

        chatScrollPane.setViewportView(messagesPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chatScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(messageLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(messageTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chatScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(messageLabel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
		try {
			Client.deconnexion();
			System.exit(0);
		} catch (RemoteException ex) {
			Logger.getLogger(FenetreMessages.class.getName()).log(Level.SEVERE, null, ex);
		}
	}//GEN-LAST:event_formWindowClosed

	private void messageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageTextFieldActionPerformed
		String message = messageTextField.getText();
		if (!message.equals("")) {
			messageTextField.setText("");
			try {
				Client.envoyerMessage(message);
			} catch (RemoteException ex) {
				Logger.getLogger(FenetreMessages.class.getName()).log(Level.SEVERE, null, ex);
			}
		}
	}//GEN-LAST:event_messageTextFieldActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane chatScrollPane;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JTextField messageTextField;
    private javax.swing.JPanel messagesPanel;
    // End of variables declaration//GEN-END:variables
}
